language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-simple-ng' ]; then cd .. && eval "mv $currentfolder generator-simple-ng" && cd generator-simple-ng; fi

